from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from benchmarks.run_aislands_isolation_adequacy import (
    EXPECTED,
    bootstrap_interval,
    build_prepared,
    component_labels,
    find_unique_sha,
    fit_probabilities,
    load_cohort,
    load_presence_sets,
    reduce_constant_columns,
    sign_flip_p,
)
from eog.prepared_island_connectivity import prepare_island_connectivity


ROOT = Path(__file__).resolve().parents[1]


def test_frozen_input_hash_contract_is_explicit_before_outcomes() -> None:
    """Real cohort/fold/climate bytes are regenerated by the smoke workflow."""
    assert set(EXPECTED) == {
        "folds",
        "climate",
        "cohort",
        "area",
        "mainland",
        "island_data",
        "species_data",
    }
    assert all(len(value) == 64 for value in EXPECTED.values())
    assert EXPECTED["folds"] == "221a925e289347069c89354d26acfab83fa3d4bc130b56f0178b8db30ab427fa"
    assert EXPECTED["climate"] == "6ae7f4a78eea28f074ef3c3399368a4886b09d2d0714e723e957d0a99b524285"
    assert EXPECTED["cohort"] == "cf645d55b8bcc46be8a8dc5399db736bbcc20bb7114a72c79a5dee61ec918e12"


def test_primary_cohort_flag_selects_exactly_886_taxa(tmp_path: Path) -> None:
    path = tmp_path / "cohort.csv"
    rows = ["species,primary_cohort_included"]
    rows.extend(f"Species_{i:04d},1" for i in range(886))
    rows.append("Excluded_species,0")
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")

    taxa = load_cohort(path)

    assert len(taxa) == 886
    assert taxa[0] == "Species_0000"
    assert taxa[-1] == "Species_0885"
    assert "Excluded_species" not in taxa


def test_presence_mapping_uses_authoritative_list_id_to_island_id_join(tmp_path: Path) -> None:
    island_data = tmp_path / "island_data.csv"
    island_data.write_text(
        "List_ID,Island_ID\nLIST_A,10\nLIST_B,20\nLIST_C,30\n",
        encoding="utf-8",
    )
    species_data = tmp_path / "species_data.csv"
    species_data.write_text(
        "List_ID,Species_update\n"
        "LIST_A,Species alpha\n"
        "LIST_B,Species alpha\n"
        "LIST_C,Species beta\n",
        encoding="utf-8",
    )

    mapped = load_presence_sets(
        species_data,
        island_data,
        {"10", "20", "30"},
        ["Species alpha", "Species beta"],
    )

    assert mapped == {
        "Species alpha": {"10", "20"},
        "Species beta": {"30"},
    }


def test_existing_authoritative_l2_engine_can_score_synthetic_heldout_rows() -> None:
    x_train = np.asarray(
        [
            [-2.0, -1.0],
            [-1.5, -0.5],
            [-1.0, -1.5],
            [-0.5, -0.8],
            [-0.2, -0.1],
            [0.2, 0.1],
            [0.5, 0.8],
            [1.0, 1.5],
            [1.5, 0.5],
            [2.0, 1.0],
        ],
        dtype=float,
    )
    y_train = np.asarray([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int)
    x_test = np.asarray([[-1.0, -1.0], [0.0, 0.0], [1.0, 1.0]], dtype=float)

    probabilities = fit_probabilities(x_train, y_train, x_test)

    assert probabilities.shape == (3,)
    assert np.isfinite(probabilities).all()
    assert np.all((probabilities > 0.0) & (probabilities < 1.0))
    assert probabilities[0] < probabilities[-1]


def test_constant_predictor_reduction_is_training_only_and_index_stable() -> None:
    x_train = np.asarray(
        [
            [0.0, 1.0, 5.0],
            [1.0, 1.0, 6.0],
            [2.0, 1.0, 7.0],
        ]
    )
    x_test = np.asarray([[100.0, 9.0, 8.0]])
    train_reduced, test_reduced, kept, dropped = reduce_constant_columns(
        x_train,
        x_test,
        ["var_a", "constant_in_train", "var_b"],
    )
    assert kept == ["var_a", "var_b"]
    assert dropped == ["constant_in_train"]
    assert train_reduced.shape == (3, 2)
    assert test_reduced.tolist() == [[100.0, 8.0]]


def test_geography_graph_components_follow_radius_only() -> None:
    distance = np.asarray(
        [
            [0.0, 10.0, 100.0, 120.0],
            [10.0, 0.0, 90.0, 110.0],
            [100.0, 90.0, 0.0, 10.0],
            [120.0, 110.0, 10.0, 0.0],
        ]
    )
    labels_25 = component_labels(distance, 25.0)
    labels_125 = component_labels(distance, 125.0)
    assert labels_25[0] == labels_25[1]
    assert labels_25[2] == labels_25[3]
    assert labels_25[0] != labels_25[2]
    assert len(set(labels_125.tolist())) == 1


def test_prepared_graph_has_exact_frozen_geography_scenarios() -> None:
    coords = np.asarray(
        [
            [150.0, -30.0],
            [150.1, -30.0],
            [151.0, -30.0],
        ],
        dtype=float,
    )
    prepared = build_prepared(["1", "2", "3"], coords)
    assert prepared.scenario_ids == (
        "g25_env_none",
        "g50_env_none",
        "g125_env_none",
        "g250_env_none",
    )
    assert prepared.geographic_distance_km.shape == (3, 3)
    assert len(prepared.component_labels) == 4


def test_outcome_runner_geography_partitions_match_existing_graph_builder() -> None:
    coords = np.asarray(
        [
            [150.00, -30.0],
            [150.15, -30.0],
            [150.45, -30.0],
            [151.10, -30.0],
            [152.00, -30.0],
        ],
        dtype=float,
    )
    ids = ["1", "2", "3", "4", "5"]
    new = build_prepared(ids, coords)
    env = np.column_stack([
        np.arange(5, dtype=float),
        np.arange(5, dtype=float) ** 2,
    ])
    existing = prepare_island_connectivity(
        ids,
        coords[:, 1],
        coords[:, 0],
        env,
        np.ones(5, dtype=bool),
    )
    existing_geo = [
        labels
        for scenario_id, labels in zip(existing.scenario_ids, existing.component_labels)
        if scenario_id.endswith("env_none")
    ]
    assert len(existing_geo) == 4
    for left, right in zip(new.component_labels, existing_geo):
        assert np.array_equal(left[:, None] == left[None, :], right[:, None] == right[None, :])


def test_species_macro_inference_helpers_are_deterministic() -> None:
    values = np.asarray([-0.10, -0.05, 0.01, -0.02, -0.04])
    ci_a = bootstrap_interval(values, reps=2000, seed=20260812)
    ci_b = bootstrap_interval(values, reps=2000, seed=20260812)
    p_a = sign_flip_p(values, reps=4000, seed=20260812)
    p_b = sign_flip_p(values, reps=4000, seed=20260812)
    assert ci_a == ci_b
    assert p_a == p_b
    assert ci_a[0] <= float(np.mean(values)) <= ci_a[1]
    assert 0.0 < p_a <= 1.0


def test_sha_resolver_refuses_missing_identity() -> None:
    with pytest.raises(RuntimeError, match="expected one repository file"):
        find_unique_sha(ROOT, "0" * 64)
