"""Prospective EOG v2 public package.

The v2 namespace is intentionally separate from :mod:`eog`'s frozen v0.1 public API.
Implementation modules remain internal details; public v2 work is grouped into
``reachability``, ``traversability`` and ``validation`` facades while the historical
``from eog.v2 import ...`` surface remains compatible.
"""

from .reachability import (
    AreaSupportDeclaration,
    AreaSupportResult,
    BridgeNodeImportanceResult,
    DynamicReachabilityEdge,
    DynamicReachabilityResult,
    DynamicTransitionOperator,
    FirstPassageSummary,
    IslandStateLayers,
    NetworkFluxDiagnostics,
    SCENARIO_IDS,
    SyntheticArchipelagoScenario,
    area_support_layers,
    assemble_island_state_layers,
    build_dynamic_reachability_visualization_payload,
    build_dynamic_transition_operator,
    build_synthetic_archipelago,
    evaluate_bridge_node_importance,
    propagate_dynamic_reachability,
    render_dynamic_reachability_html,
    summarize_first_passage,
    summarize_network_flux,
)
from .traversability import (
    DispersalMode,
    EcologicalTransitionEdge,
    OccurrenceEnvironmentalScale,
    OccurrenceRuleComparison,
    OccurrenceRuleCompatibility,
    OccurrenceTargetCompatibility,
    PathTraversabilitySummary,
    TraversabilityTransitionBundle,
    build_traversability_transition_bundle,
    compare_occurrence_transition_rules,
    environmental_transition_support,
    evaluate_occurrence_rule_compatibility,
    fit_occurrence_environmental_scale,
    summarize_path_traversability,
)
from .validation import (
    EventualGeneticConnectivity,
    EventualGeneticValidationBundle,
    FixedSourceOccurrenceFeatures,
    FixedSourceOccurrenceValidationResult,
    GeneticValidationConfig,
    GeneticValidationContrast,
    GeneticValidationFoldResult,
    GeneticValidationModelResult,
    GeneticValidationResult,
    OccurrenceModelScore,
    build_eventual_genetic_validation_bundle,
    build_fixed_source_occurrence_features,
    evaluate_fixed_source_occurrence_validation,
    evaluate_genetic_validation_ladder,
    infer_eventual_genetic_connectivity,
)

__all__ = [
    "DynamicReachabilityEdge",
    "DynamicReachabilityResult",
    "DynamicTransitionOperator",
    "FirstPassageSummary",
    "build_dynamic_transition_operator",
    "propagate_dynamic_reachability",
    "summarize_first_passage",
    "AreaSupportDeclaration",
    "AreaSupportResult",
    "IslandStateLayers",
    "area_support_layers",
    "assemble_island_state_layers",
    "NetworkFluxDiagnostics",
    "BridgeNodeImportanceResult",
    "summarize_network_flux",
    "evaluate_bridge_node_importance",
    "build_dynamic_reachability_visualization_payload",
    "render_dynamic_reachability_html",
    "SCENARIO_IDS",
    "SyntheticArchipelagoScenario",
    "build_synthetic_archipelago",
    "OccurrenceEnvironmentalScale",
    "EcologicalTransitionEdge",
    "TraversabilityTransitionBundle",
    "PathTraversabilitySummary",
    "DispersalMode",
    "fit_occurrence_environmental_scale",
    "environmental_transition_support",
    "build_traversability_transition_bundle",
    "summarize_path_traversability",
    "OccurrenceTargetCompatibility",
    "OccurrenceRuleCompatibility",
    "OccurrenceRuleComparison",
    "evaluate_occurrence_rule_compatibility",
    "compare_occurrence_transition_rules",
    "EventualGeneticConnectivity",
    "EventualGeneticValidationBundle",
    "infer_eventual_genetic_connectivity",
    "build_eventual_genetic_validation_bundle",
    "GeneticValidationConfig",
    "GeneticValidationFoldResult",
    "GeneticValidationModelResult",
    "GeneticValidationContrast",
    "GeneticValidationResult",
    "evaluate_genetic_validation_ladder",
    "FixedSourceOccurrenceFeatures",
    "OccurrenceModelScore",
    "FixedSourceOccurrenceValidationResult",
    "build_fixed_source_occurrence_features",
    "evaluate_fixed_source_occurrence_validation",
]

API_STATUS = "prospective-v2-development"
